import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/api-reference/sidebar";

const sidebars: SidebarsConfig = {
  userGuide: [
    {
      type: "category",
      label: "User Guide",
      collapsed: false,
      link: { type: "doc", id: "user-guide/user-guide" },
      items: [
        "user-guide/user-guide",
        "user-guide/faq",
        "user-guide/banking",
        "user-guide/clients",
        "user-guide/credits",
        "user-guide/client-portal",
        "user-guide/einvoicing",
        "user-guide/esignatures",
        "user-guide/expenses",
        "user-guide/invoices",
        "user-guide/quotes",
        "user-guide/recurring-invoices",
        "user-guide/gateways",
        "user-guide/products",
        "user-guide/payments",
        "user-guide/projects",
        "user-guide/purchase-orders",
        "user-guide/tasks",
        "user-guide/taxes",
        "user-guide/recurring-expenses",
        "user-guide/reports",
        "user-guide/subscriptions",
        "user-guide/transactions",
        "user-guide/vendors",
        "user-guide/basic-settings",
        "user-guide/advanced-settings",
      ],
    },
    {
      type: "category",
      label: "Advanced Topics",
      collapsed: true,
      items: [
        "advanced-topics/email-customization",
        "advanced-topics/custom-fields",
        "advanced-topics/import-and-export",
        "advanced-topics/qr-codes",
        "advanced-topics/templates",
        "advanced-topics/schedules",
        "advanced-topics/tax-accounting-tips",
      ],
    },
    "migration",
    {
      type: "category",
      label: "Legal",
      collapsed: true,
      items: [
        "legal/license",
        "legal/terms-of-service",
        "legal/data-privacy",
        "legal/self-hosting-data",
        "legal/self-hosting-terms",
        "legal/gdpr",
      ],
    },
  ],
  selfHost: [
    {
      type: "category",
      label: "Self Host",
      collapsed: false,
      link: { type: "doc", id: "self-host/self-host-installation" },
      items: [
        "self-host/getting-started",
        "self-host/self-host",
        "self-host/self-host-installation",
        "self-host/self-host-troubleshooting",
        "self-host/self-host-updating",
        "self-host/env-variables",
        "self-host/self-host-debug-mode",
        "self-host/self-host-white-labeling",
      ],
    },
  ],
  hosted: [
    {
      type: "category",
      label: "Hosted",
      collapsed: false,
      link: { type: "doc", id: "hosted/hosted-quickstart" },
      items: [
        "hosted/hosted-quickstart",
        "hosted/hosted-activate",
        "hosted/hosted-custom-domain",
        "hosted/hosted-migration",
        "hosted/hosted-mail",
        "hosted/hosted-stripe",
        "hosted/hosted-troubleshooting",
        "hosted/hosted-delete-account",
      ],
    },
  ],
  developerGuide: [
    {
      type: "category",
      label: "Developer Guide",
      collapsed: false,
      link: { type: "doc", id: "developer-guide/developer-guide" },
      items: [
        "developer-guide/developer-guide",
        {
          type: "category",
          label: "API",
          items: [
            "developer-guide/api/authentication",
            "developer-guide/api/clients",
            "developer-guide/api/invoices",
          ],
        },
        "developer-guide/payment-gateways",
        "developer-guide/statics",
      ],
    },
  ],
  apisidebar: apiSidebar,
};

export default sidebars;
