<?php

return [
    'user_guide' => [
        'url' => '#',
        'children' => [
            'getting_started' => '/:locale/user-guide',
            'faq' => '/:locale/faq',
            'banking' => '/:locale/banking',
            'clients' => '/:locale/clients',
            'credits' => '/:locale/credits',
            'client_portal' => '/:locale/client-portal',
            'einvoicing' => '/:locale/einvoicing',
            'esignatures' => '/:locale/esignatures',
            'expenses' => '/:locale/expenses',
            'invoices' => '/:locale/invoices',
            'quotes' => '/:locale/quotes',
            'recurring_invoices' => '/:locale/recurring-invoices',
            'payment_gateways' => '/:locale/gateways',
            'products' => '/:locale/products',
            'payments' => '/:locale/payments',
            'projects' => '/:locale/projects', 
            'purchase_orders' => '/:locale/purchase_orders',
            'tasks' => '/:locale/tasks',
            'taxes' => '/:locale/taxes',
            'recurring_expenses' => '/:locale/recurring-expenses',
            'reports' => '/:locale/reports',
            'subscriptions' => '/:locale/subscriptions',
            'transactions' => '/:locale/transactions',
            'vendors' => '/:locale/vendors',
            'basic_settings' => '/:locale/basic-settings',
            'advanced_settings' => '/:locale/advanced-settings',
        ],
    ],
    'advanced_topics' => [
        'url' => '#',
        'children' => [
            'email_customization' => '/:locale/email-customization',
            'pdf_customization' => '/:locale/custom-fields',
            'import_export' => '/:locale/import-and-export',
            'qr_codes' => '/:locale/qr-codes',
            'templates' => '/:locale/templates',
            'schedules' => '/:locale/schedules',
            'tax_accounting_tips' => '/:locale/tax-accounting-tips',
        ],
    ],
    'hosted' => [
        'url' => '#',
        'children' => [
            'quick_start' => '/:locale/hosted-quickstart',
            'activate' => '/:locale/hosted-activate',
            'custom_domain' => '/:locale/hosted-custom-domain',
            'hosted_migration' => '/:locale/hosted-migration',
            'mail_servers' => '/:locale/hosted-mail',
            'stripe_integration' => '/:locale/hosted-stripe',
            'troubleshooting' => '/:locale/hosted-troubleshooting',
            'delete_account' => '/:locale/hosted-delete-account',
        ],
    ],

];
